import 'package:hive/hive.dart';
import 'package:uuid/uuid.dart';

part 'journal_entry.g.dart'; // Generated by Hive

@HiveType(typeId: 0)
class JournalEntry extends HiveObject {
  @HiveField(0)
  late String id;

  @HiveField(1)
  late String title;

  @HiveField(2)
  late String body;

  @HiveField(3)
  late String mood; // e.g., "Joyful", "Anxious", "Sad"

  @HiveField(4)
  late DateTime createdAt;

  @HiveField(5)
  late DateTime updatedAt;

  @HiveField(6)
  late int wordCount;

  @HiveField(7)
  late double? moodScore; // 0-10

  @HiveField(8)
  late String? primaryEmotion;

  @HiveField(9)
  late List<String>? themes;

  JournalEntry({
    String? id,
    required this.title,
    required this.body,
    required this.mood,
    DateTime? createdAt,
    DateTime? updatedAt,
    int? wordCount,
    this.moodScore,
    this.primaryEmotion,
    this.themes,
  }) {
    this.id = id ?? const Uuid().v4();
    this.createdAt = createdAt ?? DateTime.now();
    this.updatedAt = updatedAt ?? DateTime.now();
    this.wordCount = body.split(' ').length;
  }
}